default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-mypy
    # ruff does not check type hint
    rev: v1.17.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.11
    hooks:
      # Run the linter, with selected rulesets (see .ruff.toml)
      - id: ruff-check
        args: ["--fix"]
        # description: linter, tries to fix error
      - id: ruff-format
